// File: limits.go
// Purpose: Validates file and line length limits following cognitive load
// principles. Enforces maximum 120 lines per file (excluding auto-generated).
// Enforces maximum 120 characters per line for readability. Excludes sqlc
// generated files which are beyond our control.
// Path: server/tools/checkers/limits.go
// All Rights Reserved. Arc-Pub.

package code

import (
	"fmt"
	"strings"

	"github.com/arc-pub/server/tools/core"
)

const (
	maxLines      = 120
	maxLineLength = 120
)

// Patterns for auto-generated files to exclude from checks.
var autoGenPatterns = []string{
	"sqlc",
	".gen.",
	"_gen.go",
	"generated",
}

// Limits checks file and line length constraints.
type Limits struct{}

// NewLimits creates a Limits checker.
func NewLimits() *Limits {
	return &Limits{}
}

// Name returns the checker identifier.
func (l *Limits) Name() string {
	return "limits"
}

// Check scans files for length violations.
func (l *Limits) Check(files []core.File) []core.Violation {
	var violations []core.Violation

	for _, f := range files {
		if isAutoGenerated(f.Path) {
			continue
		}

		if len(f.Lines) > maxLines {
			violations = append(violations, core.Violation{
				File:    f.Path,
				Line:    len(f.Lines),
				Rule:    "file-length",
				Message: fmt.Sprintf("exceeds %d lines", maxLines),
			})
		}

		for i, line := range f.Lines {
			if len(line) > maxLineLength {
				violations = append(violations, core.Violation{
					File:    f.Path,
					Line:    i + 1,
					Rule:    "line-length",
					Message: fmt.Sprintf("exceeds %d chars", maxLineLength),
				})
			}
		}
	}

	return violations
}

func isAutoGenerated(path string) bool {
	lower := strings.ToLower(path)
	for _, pattern := range autoGenPatterns {
		if strings.Contains(lower, pattern) {
			return true
		}
	}
	return false
}
